# Generated by Django 3.2.23 on 2024-05-24 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField()),
                ('total_spent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orders_count', models.IntegerField()),
                ('last_order_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('criteria', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('shop_url', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SegmentMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='segmentation.customer')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='segmentation.segment')),
            ],
        ),
        migrations.AddField(
            model_name='segment',
            name='customers',
            field=models.ManyToManyField(through='segmentation.SegmentMembership', to='segmentation.Customer'),
        ),
        migrations.AddField(
            model_name='segment',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='segmentation.store'),
        ),
        migrations.AddField(
            model_name='customer',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='segmentation.store'),
        ),
    ]
