# Generated by Django 3.2.23 on 2024-05-25 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='shop_url',
            new_name='store_domain',
        ),
        migrations.AddField(
            model_name='store',
            name='access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
